<?php

if(!is_dir('db/schemas')) mkdir('db/schemas');
$result = mysql_query("SHOW tables") or die("Error in query: \n" . mysql_error() . "\n");
while ($row = mysql_fetch_array($result, MYSQL_NUM)){
	generate_schema($row[0]);
}

function generate_schema($model){
	global $mysql;
	$cols = array();

	$result = mysql_query("DESCRIBE `$model`") or die("Error in query: $sql \n" . mysql_error() . "\n");
	while ($row = mysql_fetch_array($result, MYSQL_ASSOC)) $cols[$row['Field']] = $row;
	
	$yaml = YAML::encode($cols);
	$comments = "# This file is auto-generated by script/generate_schema \n# Do not edit or you'll ruin Christmas!!\n\n";
	file_put_contents("db/schemas/$model.yml", $comments . $yaml);
}
